services:
  postgres-db:
    image: postgres:15-alpine
    container_name: novastock-db
    environment:
      - POSTGRES_DB=novastock_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: